### ISSUE TITLE
Introduce Request logging middleware

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#115]
**Is your feature request related to a problem? Please describe.**
In certain scenarios you'd like to log every inbound request. It would be ideal if we provide middleware that does this out-of-the-box.

**Describe the solution you'd like**
We can introduce a `RequestTrackingMiddleware` that uses https://github.com/arcus-azure/arcus.observability/issues/14.

Things to keep in mind:
- Configuration should be provided in what should be logged:
    - Headers only, body only, headers and body, none of both, etc.
- We should provide sanitization out-of-the-box, with possibility to provide custom sanitization (based on inheritance)

**Describe alternatives you've considered**
I remember looking at [Serilog.AspNetCore's Request logging](https://github.com/serilog/serilog-aspnetcore#request-logging) which didn't feel good enough for me but can't remember why.

I think it was because it didn't work nicely with Azure Application Insights but I'm not sure.

**Comment by stijnmoreels** [comment]
> Describe alternatives you've considered
>I remember looking at Serilog.AspNetCore's Request logging which didn't feel good enough for me but can't remember why
>
> I think it was because it didn't work nicely with Azure Application Insights but I'm not sure.
Maybe because the request logging only logs the after the response is created. And I think it's rather minimal.

**Comment by tomkerkhove** [comment]
That's ok, but it's more because it logs it as a trace and not AI request which is not ideal if you ask me

**Comment by tomkerkhove** [comment]
https://github.com/arcus-azure/arcus.observability/pull/35 is now merged and work can be started.

**Comment by stijnmoreels** [comment]
Maybe besides configuring "headers" or "no headers", also which headers. Bc, security headers with secret values is maybe not a good idea to log in plain text.

**Comment by tomkerkhove** [comment]
We should do this indeed but via this approach:
> We should provide sanitization out-of-the-box, with possibility to provide custom sanitization (based on inheritance)

So it's either headers or no headers, if headers are added then our sanitization will remove documented headers out-of-the-box; but I would not make it configurable as they can extend/override our sanitization
