### ISSUE TITLE
Foresee for shared-access-key authentication through attributes

### ISSUE THREAD

**Issue by SamVanhoutte** [arcus-azure/arcus.webapi#12]
**Problem description**
Quite often (especially in backend integration), a secret key is needed for simple and easy to configure API authentication.  This feature should help in getting a fast solution.

**Solution description**
A declarative way to tag operations on API controllers with an Authorize attribute that refers to a SharedAccessPolicy is required will allow users to specify the needed authentication handler to authorize calls to the operation.

A sample implementation is already made by @SamVanhoutte (inspired by Frederik Gheysels)

**Comment by tomkerkhove** [comment]
@SamVanhoutte Can you elaborate on the sample implementation that you've used?

This approach should be using the `ISecretProvider` (https://github.com/arcus-azure/arcus.security/issues/20) in my opinion.

**Comment by tomkerkhove** [comment]
The sample Sam mentioned is available here - https://gist.github.com/tomkerkhove/e44e4e84f1f85acc37540fa941a5401b

**Comment by tomkerkhove** [comment]
We'll introduce a new attribute that inherits from `ActionFilterAttribute` which will handle this authentication.

It should provide the capability to :
- Configure name of the header to check
- Configure name of the secret that contains the key

The attribute will use CachedSecretProvider and if the key is not correct, it will return an `HTTP 401 Unauthorized`.

We want to be able to plug this in the general pipeline via startup and will see if we can use it on a per-controller and/or per-operation bases if we can inject dependencies. _([Good read](https://stackoverflow.com/questions/36109052/inject-service-into-action-filter/36109690))_

Thanks for the feedback & input @stijnmoreels &	@fgheysels!

**Comment by tomkerkhove** [comment]
Any suggestions for a clear name? How about `SharedAccessKeyAuthenticationAttribute`?

**Comment by tomkerkhove** [comment]
Implemented and released in https://github.com/arcus-azure/arcus.webapi/releases/tag/v0.1.0-preview-2.

@stijnmoreels would you mind providing some documentation on how to use this feature?
