### ISSUE TITLE
Support for JWT authorization validation

### ISSUE THREAD

**Issue by gverstraete** [arcus-azure/arcus.webapi#120]
**Describe the solution you'd like**
At the moment every project is trying to embrace Managed Identity as much as possible, so as well between Azure API Management & App Service API's.

It would be great to have an AuthorizationFilter which validates on tokens based on a specified property.
We did a similar thing at a project where we are working at the moment. But I hear from others this is also for them interesting.

**Comment by tomkerkhove** [comment]
Certainly interesting - Are you willing to contribute this?

**Comment by gverstraete** [comment]
Yes! But due to time constraints this will be very difficult the upcoming months.

**Comment by tomkerkhove** [comment]
No worries, I'll get this going and you can then review maybe?

**Comment by tomkerkhove** [comment]
Started working on this, here's my checklist:
- [ ] Implement first rough version
- [ ] Provide configuration options
- [ ] Provide documentation
- [ ] Provide more user-friendly way of wiring things up, if possible
- [ ] Provide tests

**Comment by tomkerkhove** [comment]
@fgheysels @gverstraete @stijnmoreels Have you generated JWT tokens on the fly for your unit tests before?

**Comment by gverstraete** [comment]
yes :)

**Comment by gverstraete** [comment]
Here you have a sample which will help you 

public JwtSecurityToken CreateToken(ClaimsPrincipal principal, AuthorizationGrantCodeType type)
{
            var creds = new SigningCredentials(new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration.JwtSigninKey)), SecurityAlgorithms.HmacSha256);
            DateTime expirationTime = default;

            switch (type)
            {
                case AuthorizationGrantCodeType.Bearer:
                    expirationTime = DateTime.Now.AddMinutes(_configuration.BearerExpirationTime);
                    break;
                case AuthorizationGrantCodeType.SAD:
                    expirationTime = DateTime.Now.AddMinutes(_configuration.SadExpirationTime);
                    break;
            }

            return new JwtSecurityToken(
                issuer: _configuration.JwtIssuer,
                audience: _configuration.JwtAudience,
                claims: principal.Claims,
                expires: expirationTime,
                signingCredentials: creds
            );
}

Sorry for the crappy UI; github doesn't seem to like my snippet.

System.IdentityModel.Tokens.Jwt is the namespace

**Comment by tomkerkhove** [comment]
@stijnmoreels will pick up the testing part with real JWT tokens, I will pick up the documentation side of things.

**Comment by tomkerkhove** [comment]
Any update on this testing side @stijnmoreels ?

**Comment by stijnmoreels** [comment]
> Any update on this testing side @stijnmoreels ?

Between things I'm doing that. I figured I needed an OpenApi test server that I can set up during tests, so I used `IdentityServer4` for that. So far, the test is sending to this instance, but the signature that I set up during the test is not yet validated correctly by the `JwtTokenReader`.

**Comment by tomkerkhove** [comment]
Oh good to hear! Maybe @gverstraete can help you with the testing side if you have questions?

**Comment by gverstraete** [comment]
Stijn, no need for an openid IdentityServer. You can do token creation in Post man :). Let me know more specifics on the JwtTokenReader if needed

**Comment by stijnmoreels** [comment]
> Stijn, no need for an openid IdentityServer. You can do token creation in Post man :). Let me know more specifics on the JwtTokenReader if needed

So what are you saying exactly? I should use Postman to generate a token and use that in the test? 
What you say about the `JwtTokenReader`, this part calls the OpenId server URL which is configured during the test and validates the HTTP request bearer token with the signature that it gets from the server. 

It was my understanding that I had to match client secrets but that didn't result in a valid signature response.

If you mean use Postman for testing, then this is proably not what we need. We require automated testing for this. And since the `JwtTokenReader` is set up the way it does, we required some external source to control the response. Like an OpenId `IdentityServer4` that is set up during test setup.

**Comment by gverstraete** [comment]
When you generate a token, you don't know the secret anymore. So you need to validate at another point.

You can automate postman collections, but indeed the identity server is also an option. Did not think about that.

**Comment by stijnmoreels** [comment]
> You can automate postman collections, but indeed the identity server is also an option. Did not think about that.

Do you have an example or guidance for this to set up? I think I got it working somehow but the configurations/signing keys I try to set up in the identy server are probably not yet correct to work with the JWT bearer token I send in the HTTP request.

**Comment by stijnmoreels** [comment]
> Started working on this, here's my checklist:
> 
> * [x]  Implement first rough version
> * [x]  Provide configuration options
> * [x]  Provide documentation
> * [x]  Provide more user-friendly way of wiring things up, if possible
> * [x]  Provide tests
> * [x]  Improve references for `Microsoft.AspNetCore.Mvc` with `netcoreapp3.1` (see #124)

@tomkerkhove , I can close this, right? All items are done.
