### ISSUE TITLE
Write web API v1.0 blog post

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#128]
Write blog post about what web API v1.0 introduces

**Comment by stijnmoreels** [comment]
v0.4?

**Comment by tomkerkhove** [comment]
No, 0.5 but you can write one on 0.4 if you want as well

**Comment by stijnmoreels** [comment]
Can I make a WP page for this? Since we merged it ?

**Comment by tomkerkhove** [comment]
Definately!

**Comment by stijnmoreels** [comment]
Ok, done and added a task in the Microsoft planner as well.

**Comment by stijnmoreels** [comment]
Published: https://www.codit.eu/blog/out-of-the-box-request-tracking-simplified-http-correlation-jwt-authorization-in-arcus-web-api-v1-0/
