### ISSUE TITLE
Should we merge Arcus.WebApi.Logging & Arcus.WebApi.Correlation?

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#134]
**Is your feature request related to a problem? Please describe.**
Should we merge Arcus.WebApi.Logging & Arcus.WebApi.Correlation into one 📦 as they are related?

/cc @fgheysels @gverstraete

**Comment by gverstraete** [comment]
My personal favour would be to merge it into one. I don't think we would have one api where we don't want to use the functionalities from both

**Comment by tomkerkhove** [comment]
Ok, and what do you think of naming it Arcus.WebApi.Observability to align with our other package and since it's more than logging?

**Comment by fgheysels** [comment]
Isn't it both related to logging ? Correlation adds correlation between logs ?  So I think Arcus.WebApi.Logging would be ok.  It's imo a better name then Observability, since ppl immediately will understand that it is related to logging, whereas with Observability you do not have that 'click'.
/my 2 cents

**Comment by tomkerkhove** [comment]
It's actually more than that:
- Correlation middleware to interact with req/resp to add/read headers
- Enrich telemetry with correlation information
- Exception middleware
- Request tracking middleware (TODO)

If you consider all of those logging, then that's ok but logging feels to me to just writing traces; and not metrics, events et al.

**Comment by fgheysels** [comment]
I'd consider all of these things to be logging as well , but maybe I'm wrong :)
I'm ok with observability as well.

**Comment by tomkerkhove** [comment]
I was just asking, no worries!

Are you of same opinion as @fgheysels, @gverstraete @MassimoC @mbraekman @SamVanhoutte ?

**Comment by gverstraete** [comment]
I think I more tend to agree with fgheysels :)

**Comment by tomkerkhove** [comment]
@gverstraete With that you mean `.Logging`, right?

Just to verify.

**Comment by tomkerkhove** [comment]
I agree with merging both into one package but I'm not convinced about the naming, certainly since we have `Arcus.Observability`. I'm leaning towards going with that but don't want to offend your opinions 🤔 

What would you do @SamVanhoutte ?

**Comment by SamVanhoutte** [comment]
I like Logging more, as Observability makes me think 'as an outside user' of reactive programming against things you observe for change.

**Comment by tomkerkhove** [comment]
Ok, let's go with `Arcus.WebApi.Logging` then @stijnmoreels!
