### ISSUE TITLE
Make it easy to use correlation with Azure Function

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#139]
Make it easy to use correlation with Azure Function to use correlation for example.

**Comment by stijnmoreels** [comment]
Can you give some guidance and direction to what should be achieved here? Thanks.

**Comment by stijnmoreels** [comment]
I think you send me something about this but can't find it anymore. Could you post it here?
It had something to do with some 'parent' class you made to get a more consumer-friendly way of getting/setting the correlation in an Azure function.

**Comment by tomkerkhove** [comment]
We should move this into `Arcus.WebApi.AzureFunctions` or `Arcus.WebApi.Logging.AzureFunctions`
