### ISSUE TITLE
Provide a global exception handler

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#14]
Provide a global exception handler that can be plugged in the middleware and catches unhandled exceptions. These are wrapped in an `application/problem+json` response.

Adding @massimoc given he will probably want to add more input.

**Comment by tomkerkhove** [comment]
@MassimoC For unhandled exceptions I'm actually not sure if we should return an application/problem+json, would that be recommended? I presume it should be?

**Comment by tomkerkhove** [comment]
We should determine what the state of .NET is and otherwise use https://github.com/khellang/Middleware as a basis.

**Comment by MassimoC** [comment]
The current .NET implementation is not enough. The middleware of khellang is seems to be the best approach as today.

**Comment by fgheysels** [comment]
I'm picking up this issue, and I also wonder if we should use a problem+json response when an unhandled exception is being caught.  I mean, you would want to expose as less implementation details on what went wrong to the outside, do you ?

**Comment by tomkerkhove** [comment]
That's a good point and a I agree on that, we should just return an HTTP 500 without details towards the client.

**Comment by tomkerkhove** [comment]
Implemented and released in https://github.com/arcus-azure/arcus.webapi/releases/tag/v0.1.0-preview-exception-middelware.

@fgheysels will provide docs later next week/this month.
