### ISSUE TITLE
Provide documentation on how to use AzureManagedIdentityAuthorizationFilter

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.webapi#142]
It seems that there's no documentation available yet on how to use the `AzureManagedIdentityAuthorizationFilter` class.  It would be helpfull if there was a simple how-to guide available :)

**Comment by tomkerkhove** [comment]
That's correct, we're tracking it as part of https://github.com/arcus-azure/arcus.webapi/issues/120; seems like it slipped through our releases already 😅

**Comment by tomkerkhove** [comment]
Ok if we close in favor of #120?

**Comment by tomkerkhove** [comment]
https://webapi.arcus-azure.net/features/security/auth/jwt
