### ISSUE TITLE
Provide a validation handler

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#15]
Provide a validation handler that will handle model validation failures in the middleware and return an `application/problem+json`response.

Adding @massimoc given he will probably want to add more input.

**Comment by MassimoC** [comment]
validation handler example here : https://www.strathweb.com/2018/07/centralized-exception-handling-and-request-validation-in-asp-net-core/

**Comment by fgheysels** [comment]
Isn't this something that is mostly handled by the `ApiControllerAttribute` that is available since .NET Core 2.1 ? ([Some more info](https://docs.microsoft.com/en-us/aspnet/core/web-api/index?view=aspnetcore-2.1#automatic-http-400-responses))

**Comment by tomkerkhove** [comment]
That's right, closing
