### ISSUE TITLE
Provide support for paging

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#155]
Provide support for paging by providing an easy approach to report paging information.

**Comment by tomkerkhove** [comment]
Requested by @MassimoC; feel free to add more info

**Comment by fgheysels** [comment]
Paging is something that is related to your database as well.  
The only part of 'paging' that belongs inside the WebApi project is imho a class that can be used to represent a header that contains PaginationInfo, something like this:

```csharp
 public class PaginationInfo
{
        public const string HeaderName = "x-pagination";

        public int TotalCount { get; }
        public int TotalPages { get; }
        public int PageSize { get; }
        public int CurrentPage { get; }
        public bool HasNext { get; }
        public bool HasPrevious { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaginationInfo"/> class.
        /// </summary>
        public PaginationInfo(int totalCount, int totalPages, int pageSize, int currentPage)
        {
            TotalCount = totalCount;
            TotalPages = totalPages;
            PageSize = pageSize;
            CurrentPage = currentPage;
            HasNext = CurrentPage < TotalPages;
            HasPrevious = CurrentPage > 1;
        }
}
```

And maybe an ObjectResult class which uses the above class to make sure that this information is included as a header, so that you can write something like this in your controller:

```csharp
const int pageSize = 25;

var query = new GetProductsQuery(productNameSearchCriterium, categorySearchCriterium, pageSize, page);

var result = await _mediator.Send(query);

var model = _mapper.Map<IEnumerable<Models.Product>>(result.Items);
            
return new OkPaginatedObjectResult(model,
                                            new PaginationInfo(result.TotalCount, result.TotalPages, result.PageSize, result.PageNumber));
```

How the paging itself is implemented (at DB level), is totally up to the component that retrieves the information from the backing datastore.

Any thoughts @MassimoC  ?

**Comment by fgheysels** [comment]
If we agree on how to deal with this, I'm willing to pick up this issue.

**Comment by MassimoC** [comment]
This makes sense to me. 
[OFF TOPIC] On the other hand, this is a very opinionated topic so I suppose many devs prefer having the pagination as part of the response body together with the links.
I was wondering whether Arcus could/should choose and implement a custom media type

**Comment by fgheysels** [comment]
It is indeed opinionated.   Some API's return this information in the response headers, others in the body.
Then, my opinion would be that Arcus should not enforce an opinion on customers, and thus, opinionated things like pagination should not be in Arcus.

**Comment by stijnmoreels** [comment]
We can close this, then, I think?

**Comment by fgheysels** [comment]
Yes, I think we can close  this issue.
