### ISSUE TITLE
Provide operation filter for SAS key authentication with Swashbuckle

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#170]
**Is your feature request related to a problem? Please describe.**
Provide operation filter for SAS key authentication with Swashbuckle so that it's possible to add it as a security requirement.

This can already be done with `AddSecurityRequirement` which applies it globally, but sometimes the auth is not covered for all operations.

**Additional context**

- [Docs](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements)

**Comment by begonias** [comment]
This feature will be a time-saver (and avoids complexity or non-standard implementation of own AuthorizationHeaderOperationsFilter).
Do have a slightly off-topic question.
What is the intended use of SAS authentication on WebApi as opposed to client certificate and/or JWT?

**Comment by tomkerkhove** [comment]
It's just a matter of what's needed in terms of security, sometimes SAS authentication is more than enough while in other scenarios they want to use client certificate or JWT.

Not really a solid answer but merely giving different options.
