### ISSUE TITLE
Allow optional jwt token validation using the oid

### ISSUE THREAD

**Issue by MichielVanwelsenaere** [arcus-azure/arcus.webapi#175]
**Is your feature request related to a problem? Please describe.**
In the current implementation the `JwtTokenAuthorizationFilter` verifies the `aud` value in the jwt token. That `aud` value is set to what is requested by the client and can be multiple things. I'm currently facing a scenario where we want to secure the last mile between APIM and backend App Services. The APIM instance is allowed to call the App Services and nothing else thus my idea was the following:
1. in the Apim policy request a MSI token (resource audience doesn't matter). Because the APIM resource is used to request the jwt token the `oid` will be automatically set to the MSI objectId of the APIM resource.
2. Validate in the app service code whether the jwt token passed has the expected `oid` value containing the MSI objectId of the APIM resource.

**Describe the solution you'd like**
An adjustment of the `JwtTokenAuthorizationFilter` so it allows for filtering on `oid` and/or `aud`. This depending on the needs of the application/developers. 

**Describe alternatives you've considered**
None 

**Additional context**
This suggested feature assumes the following:
1. it's not possible for any resource/client to request a jwt token with a configurable `oid` value on the Microsoft OpenID endpoint.

**Comment by fgheysels** [comment]
Is `oid` something that is Microsoft specific ?  It seems to be the object-id of an Azure user / application ?  Wouldn't this be to 'Azure specific', or is that something that doesnt matter, as Arcus is already pretty tied to Azure ?

Can't we use `sub` instead ?  (Would need to investigate what it contains in this particular scenario)

**Comment by MichielVanwelsenaere** [comment]
> 
> 
> Is `oid` something that is Microsoft specific ? It seems to be the object-id of an Azure user / application ? Wouldn't this be to 'Azure specific', or is that something that doesnt matter, as Arcus is already pretty tied to Azure ?
> 
> Can't we use `sub` instead ? (Would need to investigate what it contains in this particular scenario)

Could be that `oid` is Microsoft specific. `sub` has the same value as `oid` in this particular scenario.

**Comment by MichielVanwelsenaere** [comment]
perhaps interesting as well could be `xms_mirid` as that contains the resourceId of the resource that requested the token. Perhaps it makes sense to allow checking of one or more configurable values (`aud`,`oid`, `xms_mirid`, etc..)?

**Comment by gverstraete** [comment]
This Arcus library must work for all Jwt Tokens, and not specifically for Managed Identity keep this in mind! As far as I remember is the `aud` the object/applicationId of the application creating the token. So I think you have everything?

**Comment by MichielVanwelsenaere** [comment]
Actually, from our experience, the `aud` token contains the requested resource:
`"aud": "https://management.azure.com/"`
and that's with the following in the apim policy:
```xml
<authentication-managed-identity resource="https://management.azure.com/"/> <!--Azure Resource Manager-->
```

**Comment by fgheysels** [comment]
The audience (`aud`) contains the protected resource.  (Who should accept this token, who is the audience for this token).
So, if you have an API which is protected by a jwt token, that API should accept tokens that refer to that api in the `aud` claim of the token.  If the `aud` is not as expected, the request should be rejected.

https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#payload-claims

**Comment by tomkerkhove** [comment]
I'm not an expert on this topic so all PRs are welcome!

**Comment by MichielVanwelsenaere** [comment]
I agree that it makes sense to not make this MS specific, any thoughts on how this generic structure should look like? 
Perhaps something like the below?
```C#
services.AddMvc(mvcOptions => 
        {
            string applicationId = "e98s9-sadf8981-asd8f79-ahtew8";
            string claim = "oid";
            mvcOptions.Filters.AddJwtTokenAuthorization(options => options.JwtTokenReader = new JwtTokenReader(claim, applicationId));
        });
```

**Comment by fgheysels** [comment]
I would indeed do something as you suggest above, although I 'd improve the interface a bit.
Something like this:

```csharp
services.AddMvc(mvcOptions => 
{
    mvcOptions.AddJwtTokenAuthorization(options =>
   {
       var claimChecks = new [] 
                         {
                             new ClaimCheck("aud", "e98s9-sadf8981-asd8f79-ahtew8"),
                             new ClaimCheck("oid", "..."),
                             new ClaimCheck("sub", "...")
                         };

       optiosn.JwtTokenReader = new JwtTokenReader(claimChecks);
   }
});
```

**Comment by tomkerkhove** [comment]
_Adding @egeda9 who is implementing this, thanks! 🙏_

So if I get it right, you want to have more flexibility in what claims are verified - Either validate `aud` like it is today, switch to `oid` or even have a whole list of things to check. Is that correct?

If so, I agree with @fgheysels his approach to do so.

So instead of this:
```csharp
services.AddMvc(mvcOptions => 
{
    var parameters = new TokenValidationParameters();
    string endpoint = "https://localhost:5000/.well-known/openid-configuration";
    mvcOptions.Filters.AddJwtTokenAuthorization(options => options.JwtTokenReader = new JwtTokenReader(parameters, endpoint));
});
```

What if it would be more like this:

```csharp
var claimChecks = new [] 
{
    new ClaimCheck("aud", "e98s9-sadf8981-asd8f79-ahtew8"),
    new ClaimCheck("oid", "..."),
    new ClaimCheck("sub", "...")
};

services.AddMvc(mvcOptions => 
{
    var parameters = new TokenValidationParameters();
    string endpoint = "https://localhost:5000/.well-known/openid-configuration";
    mvcOptions.Filters.AddJwtTokenAuthorization(claimChecks, options => options.JwtTokenReader = new JwtTokenReader(parameters, endpoint));
});
```

@stijnmoreels Out-of-scope here but what if we improve the UX of our extension so that they provide parameters and endpoint and we assign it to the JwtTokenReader under the hood (with still the option to provide their own)?

**Comment by stijnmoreels** [comment]
> @stijnmoreels Out-of-scope here but what if we improve the UX of our extension so that they provide parameters and endpoint and we assign it to the JwtTokenReader under the hood (with still the option to provide their own)?

Yes, that seems appropriate. but we also have already defaults for these, right? So, we still have to provide the option to not include all these. (Plus, this is '_providing reader_' is somewhat related to a revisit I did on this security filter here: #176).

**Comment by tomkerkhove** [comment]
I'll have a look at that PR and agree there are defaults but we shouldn't ask users to change the reader directly but just accept the parameters if they don't want to provide their own JwtTokenReader; no?

**Comment by stijnmoreels** [comment]
> I'll have a look at that PR and agree there are defaults but we shouldn't ask users to change the reader directly but just accept the parameters if they don't want to provide their own JwtTokenReader; no?

Yes, of course. I agree! Just pointing out that we should still provide overloads were we can change it.

**Comment by egeda9** [comment]
I've created the PR [https://github.com/arcus-azure/arcus.webapi/pull/179](url) trying to follow the proposal made here [https://github.com/arcus-azure/arcus.webapi/issues/175#issuecomment-689984153](url). Please let me know if this PR fulfills what is expected as the desired behavior.
