### ISSUE TITLE
Provide middleware that automatically adds X-Version header

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#180]
**Is your feature request related to a problem? Please describe.**
Provide middleware that automatically adds X-Version header

**Describe the solution you'd like**
Would be nice to have this as middleware for all our endpoints.

Ideally, we can configure the HTTP header name that is being used.

**Additional context**
Depends on https://github.com/arcus-azure/arcus.observability/issues/143.

**Comment by stijnmoreels** [comment]
Ah, yes, but not in production mode? Seems like not a good idea to expose the version like this?

**Comment by tomkerkhove** [comment]
I don't see the problems with that? It helps during support cases and/or can be only for internal service-to-service communication.

It's just a version, nothing more than that.

**Comment by stijnmoreels** [comment]
Yes, but it leaks information in that way. Issues in previous versions can be very quick searched for and maybe exposed. Just like we hide the versions of other systems, it seems logic to hide it for our own system as well. But, indeed, for non-production mode this can be useful.

**Comment by tomkerkhove** [comment]
Even for production, I think it makes sense given it allows you to collaborate with other teams inside the company on issues in a microservices world.

It helps to troubleshoot bugs and understand on what version another component is. Do we need it outside of the company? Maybe, but maybe not given the security risk you've listed.

**Comment by stijnmoreels** [comment]
Hmm, yeah, I still have my doubts. We should then definitly document this thoroughly and explain that this should not be used in publicly available endpoints.

**Comment by fgheysels** [comment]
I wonder what an `x-version` header brings as added value for the _consumer_ of the API ?  Is the consumer interested in this value or does it only bring some extra 'clutter' ?
I do agree that knowing the version of the API or of the backing assembly can be of great value while troubleshooting, and with that perspective it might make more sense to include this information as a structured property in the logs ?  So for every request, add the version information as a property in the logs ?

**Comment by tomkerkhove** [comment]
It is indeed already added through our enrichment of logs but if you have external teams integrating with each other it's useful to know if something new is already available (for example a bug fix).
