### ISSUE TITLE
Bypass JwtTokenValidation for certain endpoints

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.webapi#184]
In a project I'm working on, we're making use of the `JwtTokenAuthorization` filter to verify if all incoming requests are coming via Azure API Management.   This works fine, but I was wondering if there is a way to bypass this validation / filter for certain endpoints.

Our API has a health endpoint, and this endpoint is called at regular intervals by Azure for checking if our API is still online.   However, due to the JwtTokenAuthorization filter that is configured, calls to this endpoint by Azure always return a HTTP 401.

Therefore, I was wondering if there are possibilities to bypass this filter for certain endpoints.

**Comment by tomkerkhove** [comment]
Not for now but it might be good to see if we can allow you to use `AllowAnonymousAttribute` and skip our authentication/authorization if it's specified. Would that be useful? (assuming we can make it so)

**Comment by fgheysels** [comment]
I was thinking of that approach, but I wonder if that would be the best solution.   `AllowAnonymous` has imo a specific meaning, which says that the user / client that is calling that endpoint does not need to be authenticated.  I think introducing a more specifc attribute might be a better solution ?

**Comment by tomkerkhove** [comment]
What would your proposal be? What if it supports both?

**Comment by stijnmoreels** [comment]
If you're not solely relying on the 'map controlers to endpoints', you can I think first map the health endpoint (ex. `app.Map`) and then add the authentication & authorization for the remaining.

Otherwise, we could indeed introduce a specific attribute or an omitted list of route paths that we can register that will not be authenticated and/or authorized.

**Comment by fgheysels** [comment]
Specifying the routes that should be ignorred when registering the filter is indeed another option.
However, I think I'm more in favor of using a specific attribute.  When you specify a list of routes that should be ignored, you'll most probably pass them in as an array of strings, but that might be harder to maintain:  if you change a route, you might need to check that list to see if there are entries that must be updated as well, and I think that might be easily forgotten.

**Comment by stijnmoreels** [comment]
> Specifying the routes that should be ignorred when registering the filter is indeed another option.
> However, I think I'm more in favor of using a specific attribute. When you specify a list of routes that should be ignored, you'll most probably pass them in as an array of strings, but that might be harder to maintain: if you change a route, you might need to check that list to see if there are entries that must be updated as well, and I think that might be easily forgotten.

Yes, again, if you use solely the approach 'map controllers to endpoints' it's maybe not a good idea. Maybe using constants for routes can help. I'll check what it would take for an extra attribute.

**Comment by stijnmoreels** [comment]
OK, that's even less complicated then I thought.

```csharp
public async Task OnAuthorizationAsync(AuthorizationFilterContext context)
{
    if (context.ActionDescriptor.EndpointMetadata.Any(m => m is SkipSharedAccessKeyAuthenticationAttribute))
    {

    }
}
```

Works for both attribute on method and controller.

**Comment by tomkerkhove** [comment]
That's fine for me, as long as Anonymous attribute is supported as well.

Do we use `SkipSharedAccessKeyAuthenticationAttribute` or `IgnoreSharedAccessKeyAuthenticationAttribute`?

**Comment by fgheysels** [comment]
or `BypassSharedAccessKeyAuthenticationAttribute` :P

**Comment by tomkerkhove** [comment]
BypassSharedAccessKeyAuthenticationAttribute it is! Can you have a look at this one please @stijnmoreels? Thanks a ton!
