### ISSUE TITLE
Provide support for response body tracking

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#199]
**Is your feature request related to a problem? Please describe.**
Provide support for response body tracking, in addition to request body tracking.

**Describe the solution you'd like**
Allow customers to opt-in through `IncludeResponseBody` which populates a new dimension called `ResponseBody` or so.

When doing this, we should:
- Introduce `RequestBody` which contains what `Body` contains today
- Deprecate `Body`, and add fixed `Request body is now available in 'RequestBody' dimension`
  - Although you could argue that's a breaking change as well, so could just add the request body twice, but that has a cost impact

**Comment by stijnmoreels** [comment]
Should this be a separate middleware component? And if not, then we should probably rename some of these components as they are no more only tracking the request.

**Comment by tomkerkhove** [comment]
Let's do a new one maybe? What is the current extension called to opt-in for request tracking?

**Comment by stijnmoreels** [comment]
> Let's do a new one maybe? What is the current extension called to opt-in for request tracking?

`.UseRequestTracking`.

**Comment by stijnmoreels** [comment]
If they are separate, then we will also have separate tracking information. As there's a different telemetry context that has to be created for the `.LogRequest`...

**Comment by tomkerkhove** [comment]
Then I'd say let's move it inside that one. Can be new middleware if you want but I'd rename it personally.

I don't think anyone uses our middleware directly.

**Comment by stijnmoreels** [comment]
And also rename the extension, then? (I mean, obsolete + new one?)

**Comment by tomkerkhove** [comment]
Ah I get your confusion - With request tracking I also understand response but probably you are not?

**Comment by stijnmoreels** [comment]
> Ah I get your confusion - With request tracking I also understand response but probably you are not?

Ah, no, indeed 😅 .

**Comment by tomkerkhove** [comment]
@fgheysels WDYT?

For me request tracking includes its response as it's one operation, but who am I 🤷‍♂️

It's also called a Request in Application Insights.

**Comment by stijnmoreels** [comment]
I'll also add a request- and response body buffer to have a safeguard against malicious requests/responses.

**Comment by stijnmoreels** [comment]
Hmm, I'll leave it in the request tracking middleware, as it's indeed also named this way in Application Insights and we don't want to confuse people.
