### ISSUE TITLE
Provide capability to opt-in for security events

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#225]
**Is your feature request related to a problem? Please describe.**
Provide capability to opt-in for security events so that consumers can choose if they want to have them or not.

**Describe the solution you'd like**
Having an opt-in would be nice since it tends to generate a lot of telemetry if it's turned on by default.

**Additional context**
We are currently seeing a high volume of security events while we are not interested in them for the time being.

![image](https://user-images.githubusercontent.com/4345663/116546745-464dfc00-a8f2-11eb-8c14-2d38f30e1b04.png)

**Comment by fgheysels** [comment]
What exactly are those security events ?

**Comment by tomkerkhove** [comment]
It reports when somebody authenticates and all - https://github.com/arcus-azure/arcus.webapi/blob/master/src/Arcus.WebApi.Security/Authentication/SharedAccessKey/SharedAccessKeyAuthenticationFilter.cs#L158

**Comment by fgheysels** [comment]
I wonder if we should even log some of these ?  I mean should we log events in this case if authentication was successful ?  I honestly don't see any added value in this.

**Comment by tomkerkhove** [comment]
I think having them in there for auditing can be OK, but only if it's opt-in

**Comment by stijnmoreels** [comment]
Is this something you want to configure generally or something specific in the options of the authentication mechanisms...
If it's general, then we don't have anything already so it would be something new just for that?

**Comment by tomkerkhove** [comment]
I would do it generally indeed

**Comment by stijnmoreels** [comment]
> I would do it generally indeed

And where? Should you have something on the `IServiceCollection` to do this? 
```csharp
services.ConfigureAuditing(options => options.IncludeSecurityEvents = true)
```

**Comment by tomkerkhove** [comment]
Ah you mean that kind of general, I was just referring to the general authentication config which would be enough for me.

**Comment by stijnmoreels** [comment]
> Ah you mean that kind of general, I was just referring to the general authentication config which would be enough for me.

Ah, so like params in the authentication filters and attributes.
