### ISSUE TITLE
UseRequestTracking logs an additional request with a wrong timestamp

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.webapi#230]
**Describe the bug**
I'm using Arcus.WebApi.Logging v1.3.1 and I've enabled `UseRequestTracking`:

```csharp
app.UseHttpCorrelation();
app.UseRouting();
app.UseRequestTracking();
app.UseAuthentication();
```

I'm also logging to Application Insights.

After enabling `UseREquestTracking`  I can see that an additional request is logged in AppInsights:

![image](https://user-images.githubusercontent.com/3605786/117042454-4b54e600-ad0c-11eb-8735-cc33b58db19c.png)

In the above screenshot, you can also see that the timestamp of that request is wrong: it is not precise enough.

The precision of the timestamp is only set to seconds, while it should be set to the tenth millions of a second (`yyyy-MM-ddTHH:mm:ss.fffffff zzz`).  (See also PR 181 in Arcus.Observability).

![image](https://user-images.githubusercontent.com/3605786/117042518-6162a680-ad0c-11eb-8e04-1090c29bb962.png)

**Comment by tomkerkhove** [comment]
Relates to https://github.com/arcus-azure/arcus.observability/pull/181

**Comment by tomkerkhove** [comment]
This is because we are still using v2.0.0 apparantly:
https://github.com/arcus-azure/arcus.webapi/blob/master/src/Arcus.WebApi.Logging/Arcus.WebApi.Logging.csproj#L33-L36

**Comment by tomkerkhove** [comment]
See https://github.com/arcus-azure/arcus/issues/129

**Comment by fgheysels** [comment]
Can this one be closed ?

**Comment by tomkerkhove** [comment]
I think we can but will let @stijnmoreels verify
