### ISSUE TITLE
Remove the PII information from the request logs automatically

### ISSUE THREAD

**Issue by gverstraete** [arcus-azure/arcus.webapi#254]
**Is your feature request related to a problem? Please describe.**
The customer requests us to not log PII information in our requests. This is currently supported by excluding headers, but not in the body. 

**Describe the solution you'd like**
I'm looking for something that would also clear out properties from the body (I know content-type wise this might be a not so easy task)

**Comment by stijnmoreels** [comment]
We can make the sanitization of the request body configurable (like the request headers) so you could write your own exclusion/alteration of the body.

**Comment by stijnmoreels** [comment]
Is this something you would like to pick up, @gverstraete?

**Comment by fgheysels** [comment]
As @gverstraete already pointed out, this can be quite a challenge, as you have different content-types to deal with and you have multiple levels of nesting in both json & xml contents.

How do you see this implemented ?  Do you want a configurable list of property-names that must be sanitized cfr how it is done with headers ?
Maybe it is more appropriate to not log the request / response bodies at all ?


Are we talking about both request & response bodies btw ?

**Comment by stijnmoreels** [comment]
> As @gverstraete already pointed out, this can be quite a challenge, as you have different content-types to deal with and you have multiple levels of nesting in both json & xml contents. 
> How do you see this implemented ? Do you want a configurable list of property-names that must be sanitized cfr how it is done with headers ? Maybe it is more appropriate to not log the request / response bodies at all ?

I think passing allong properties for the body is too specific and will always results in 'not yet supported' issues. As I suggested, we might option for overriding the sanitization of the request/response body like you can do now for the headers. As each project will have different personal info in different places. Right?

**Comment by gverstraete** [comment]
> > As @gverstraete already pointed out, this can be quite a challenge, as you have different content-types to deal with and you have multiple levels of nesting in both json & xml contents.
> > How do you see this implemented ? Do you want a configurable list of property-names that must be sanitized cfr how it is done with headers ? Maybe it is more appropriate to not log the request / response bodies at all ?
> 
> I think passing along properties for the body is too specific and will most likely often result in 'not yet supported' issues. As I suggested, we might option for overriding the sanitization of the request/response body like you can do now for the headers. As each project will have different personal info in different places. Right?
> 
> There, you could exclude your own body properties from any specific input you're currently dealing with.

I think we need to implement something with an external handler that get's a bytearray of string, where you can do what you want? 

And maybe a default one for Json as this is most used?



> Is this something you would like to pick up, @gverstraete?

I'm just raising here. I don't have the time to do this unfortunately.

**Comment by stijnmoreels** [comment]
>I think we need to implement something with an external handler that get's a bytearray of string, where you can do what you want?

Yes, that's exactly what I mean, like we did with the headers too.

> I'm just raising here. I don't have the time to do this unfortunately.

Ok, no problem, we'll take it up then. Thanks for raising this.
