### ISSUE TITLE
RequestBody is logged as an escaped JSON string

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.webapi#270]
I'm wondering why the request-bodies are saved as 'escaped' strings when using `UseRequestTracking` with `IncludeRequestBody` enabled.

When I look in Application Insights, the value of the `RequestBody` looks like this f.i.:

![image](https://user-images.githubusercontent.com/3605786/144563462-05e2929f-cc5e-444d-851e-01adc840a266.png)

Can't we log is 'as is', instead of as an escaped string ?

**Comment by stijnmoreels** [comment]
As far as I can see, we don't escape the bodies. We remove null chars, but that shouldn't impact this. Maybe this is something outside our hands?

**Comment by stijnmoreels** [comment]
This `RequestBodyDimension`, is that a custom dimension you added? Because this is not some built-in value from Arcus.

**Comment by fgheysels** [comment]
No, I created a new API project via the template, and enabled requestracking for requestbodies etc...

```csharp
app.UseRequestTracking(trackingOptions =>
{
     trackingOptions.IncludeRequestHeaders = true;
     trackingOptions.IncludeRequestBody = true;
     trackingOptions.IncludeResponseBody = true;
});
```

What dimension did you expect ?

**Comment by stijnmoreels** [comment]
`RequestBody` and `ResponseBody`. Those are telemetry values we have for this 🤔.

**Comment by fgheysels** [comment]
This is what I see:

![image](https://user-images.githubusercontent.com/3605786/144673928-aaabf9cb-2041-492b-9095-06178aa118a4.png)

and I also see a `Request` dimension which includes all sort of information about the request (verb, uri, headers and the requestbody)

**Comment by fgheysels** [comment]
> This `RequestBodyDimension`, is that a custom dimension you added? Because this is not some built-in value from Arcus.

Ok, that was a mistake of mine.  As you can see in the screenshot in my openings-post, the dimension is named `RequestBody`

**Comment by stijnmoreels** [comment]
Ok, we'll have to check how we can indeed remove these escape characters. 👍

**Comment by stijnmoreels** [comment]
I think this is now fixed with the new version of observability. We should consider upgrading, then.

**Comment by stijnmoreels** [comment]
Was fixed in the .NET 6 support PR #311 as we now use v2.4 which has this fix.
