### ISSUE TITLE
Provide capability to add JWT authentication with `IServiceProvider` to have easy access to the secret store

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.webapi#271]
**Is your feature request related to a problem? Please describe.**
Currently, when using the JWT authentication option in the Arcus Web API project template, you have to come up with your own way to get access to the `ISecretProvider` to get the symmetric key that's required for configuring the JWT authentication.

**Describe the solution you'd like**
Add an `.AddJwtBearer` extension that gives consumers access to the `IServiceProvider` 

```csharp
IServiceCollection services = ...

services.AddAuthentication(...)
        .AddJwtBearer((options, serviceProvider) =>
         {
            var secretProvider = serviceProvider.GetRequiredService<ISecretProvider>();
            string key = secretProvider.GetRawSecretAsync("JwtSigningKey").GetAwaiter().GetResult();

            options.TokenValidationParameters = new TokenValidationParameters
            {
               IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(key)),
            };
         });
```

**Comment by stijnmoreels** [comment]
@gverstraete , this would be a good thing, right? To have more cleaner access to this.

**Comment by gverstraete** [comment]
Yes, I agree! Would be a good extension!
