### ISSUE TITLE
Introduce a new `HealthReport` type to use across Arcus repo's

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.webapi#277]
**Is your feature request related to a problem? Please describe.**
When exposing the Swagger (UI) of your application with the built-in Microsoft [`HeathReport` ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.diagnostics.healthchecks.healthreport?view=dotnet-plat-ext-6.0), you get a whole lot of assembly information because the `Exception` is part of that type. This is not only unnecessary, but could expose a security risk for leaking incontrollable information.

**Describe the solution you'd like**
Create a subset of the Microsoft `HealthReport` type with information that we control and are safe to expose. This type should be easily used with the Microsoft variant, and should be serializable easily. We can then use it in our Templates Web API project template and in the TCP probe in Messaging.

**Additional context**
Related to https://github.com/arcus-azure/arcus.templates/issues/491

**Comment by stijnmoreels** [comment]
Something like this?

```csharp
public class HealthReportJson
    {
        public IDictionary<string, HealthReportEntryJson> Entries { get; set; }

        public HealthStatus Status { get; set; }

        public TimeSpan TotalDuration { get; set; }

        public static implicit operator HealthReport(HealthReportJson report)
        {
            IDictionary<string, HealthReportEntry> entries = 
                report.Entries.ToDictionary(item => item.Key, item => (HealthReportEntry) item.Value);

            return new HealthReport(
                new ReadOnlyDictionary<string, HealthReportEntry>(entries),
                report.TotalDuration);
        }
    }

    public class HealthReportEntryJson
    {
        public IDictionary<string, object> Data { get; set; }
        public string Description { get; set; }
        public TimeSpan Duration { get; set; }
        public HealthStatus Status { get; set; }
        public IEnumerable<string> Tags { get; set; }

        public static implicit operator HealthReportEntry(HealthReportEntryJson entry)
        {
            return new HealthReportEntry(
                entry.Status,
                entry.Description,
                entry.Duration,
                exception: null,
                new ReadOnlyDictionary<string, object>(entry.Data),
                entry.Tags);
        }
    }
```

**Comment by fgheysels** [comment]
Do you have a JSON serialized version/example of that proposal ? :)

**Comment by stijnmoreels** [comment]
> Do you have a JSON serialized version/example of that proposal ? :)

Well, it's the same model as Microsoft's `HealthReport`, only without the `Exception` property. So the JSON would be same, exception without the exception details.

**Comment by stijnmoreels** [comment]
Close in favor of https://github.com/arcus-azure/arcus.templates/pull/589
