### ISSUE TITLE
Documentation: Authentication samples in docs are no longer up-to-date

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.webapi#283]
The examples that show how the authentication helpers that are defined in Arcus can be used, are not up-to-date.
The samples are still using the `AddMvc` extension method which is replaced since ASP.NET Core 3.x with other methods like `AddControllers`, `AddControllersWithViews` ....

Next to that, I also wonder if the approach with using Filters is still considered as a good practice for security related things ?

(I'm talking about the samples that are shown [here](https://webapi.arcus-azure.net/features/security/auth/jwt), [here](https://webapi.arcus-azure.net/features/security/auth/shared-access-key) and [here](https://webapi.arcus-azure.net/features/security/auth/certificate))

**Comment by stijnmoreels** [comment]
The docs is definitely something we can improve. We should indeed use `.AddControllers(options => options.Filters.*)` for this. The filters used here are `IAuthentication/Authorization` filters, which are also used for other security features. Not sure if I fully get what you're going for. These filters are one of the first the request goes through.

**Comment by fgheysels** [comment]
I just wanted to implement shared access key authentication using Arcus, and I followed the docs.  
In the documentation, it is stated that you should import the `Arcus.WebApi.Security.Authentication` package but it seems to be deprecated:

![image](https://user-images.githubusercontent.com/3605786/151532468-ff9e4f11-8e71-476d-84f7-4cc55b9a4b87.png)

**Comment by stijnmoreels** [comment]
> I just wanted to implement shared access key authentication using Arcus, and I followed the docs. In the documentation, it is stated that you should import the `Arcus.WebApi.Security.Authentication` package but it seems to be deprecated:
> 
> ![image](https://user-images.githubusercontent.com/3605786/151532468-ff9e4f11-8e71-476d-84f7-4cc55b9a4b87.png)
> 
> Ok, instead of `Arcus.WebApi.Security.Authentication` it seems like it should now be `Arcus.WebApi.Security`

Ah, yes, that also something that the docs are not yet updated to. Maybe in other issue, though.

**Comment by stijnmoreels** [comment]
Is fixed in #317
