### ISSUE TITLE
Remove `AzureManagedIdentityAuthorizationFilter` from `Arcus.WebApi.Security`

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.webapi#288]
**Is your feature request related to a problem? Please describe.**
The `AzureManagedIdentityAuthorizationFilter` was an initial implementation but was later replaced by the `JwtTokenAuthorizationFilter`. This is deprecated and no longer maintained.

**Describe the solution you'd like**
Remove the `AzureManagedIdentityAuthorizationFilter` from the `Arcus.WebApi.Security` project.

**Comment by fgheysels** [comment]
Is that type already marked as obsolete ?
If not, shouldn't we do that first ?

**Comment by stijnmoreels** [comment]
> Is that type already marked as obsolete ? If not, shouldn't we do that first ?

Type is already marked as obsolete. This is a reminder that we remove it later.
