### ISSUE TITLE
Remove `AddHttpCorrelation` extension with optional parameter

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.webapi#291]
**Is your feature request related to a problem? Please describe.**
When designing the HTTP correlation, we moved towards a HTTP-specific correlation options, making the `AddHttpCorrelation` extension with the regular `CorrelationInfoOptions` obsolete.

**Describe the solution you'd like**
Remove the `AddHttpCorrelation` extension with the optional regular `CorrelationInfoOptions` parameter.

**Comment by fgheysels** [comment]
In that case, we also must make sure to modify the documentation:
https://webapi.arcus-azure.net/features/correlation


Although the overload that requires you to specify the options offers more flexibility, I do think it is definitely not easier to use this out of the box if you just want to rely on default values

**Comment by stijnmoreels** [comment]
Yes, the trick would be here, to introduce also a new overload with ni parameters, sonwe get the defaults there.
We can't do that yet bc of this optional parameter.

**Comment by stijnmoreels** [comment]
Done implicitly via #336 .
