### ISSUE TITLE
Add default HTTP correlation `.AddHttpCorrelation` extension

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.webapi#293]
**Is your feature request related to a problem? Please describe.**
When designing the HTTP correlation, we chose to update the correlation options to a HTTP-specific ones. This made the existing extension with optional parameter obsolete (see #291).

**Describe the solution you'd like**
When the `.AddHttpCorrelation` extension is removed with the optional parameter, we can add a new one without any parameters which will result in the default `HttpCorrelationInfoOptions` values.

The documentation doesn't have to be adapted, in this case, bc it was first pointing to the optional extension and will now point to the empty-parameter one.

- [ ] Add default HTTP correlation `.AddHttpCorrelation` extension for common Web API projects
- [ ] Add default HTTP correlation `.AddHttpCorrelation` extension for Azure Functions projects

**Comment by fgheysels** [comment]
Should this be done in conjunction with https://github.com/arcus-azure/arcus.webapi/issues/291
(same PR ? )

**Comment by stijnmoreels** [comment]
> Should this be done in conjunction with #291 (same PR ? )

Could be, yeah. Don't know who's gonna pick it up. A newcommer might want to split it, if it's one of us, I think it will be done together.

**Comment by stijnmoreels** [comment]
Done implicitly in #336 .
