### ISSUE TITLE
AppInsights is transitioning to W3C TraceContext

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.webapi#309]
As can be read [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation#correlation-headers-using-w3c-tracecontext), Application Insights is transitioning to TraceContext standard.

This means that some headers like `Request-Id' will be deprecated as far as I understand from the above article.

I believe that we will have some work to do in order to support this change, since I've seen that our `CorrelationMiddleware` in Arcus.WebApi is using the `CorrelationInfoUpstreamServiceOptions` to correlate, where the default header-name that is used to correlate is `Request-Id`.

Although the article states that backward compatiblity will be maintained, I feel we should defnitily investigate what these changes mean to the functionality provided by Arcus, and we must consider moving to this W3C std as well.

To be further investigated.

**Comment by stijnmoreels** [comment]
### Current situation
When a request is received, following headers are inspected:
* `X-Transaction-Id`: becomes the `TransactionId` in the correlation
* `Request-Id`: contains both the operation and operation parent ID:
    * When matches the correct format, returns the root ID as the `OperationId`
    * Otherwise use the `X-Operation-Id` header for the `OperationId`
    * The entire value is used as the `OperationParentId` in the correlation

### New situation
When a request is received, following headers should be inspected:
* `traceparent`: contains both the transaction ID and the operation parent ID
    * `trace-id` becomes `OperationId`
    * `parent-id` becomes `OperationParentId`
* `tracestate`: contains a set of encoded sets of the `traceparent` and seems like a good one for the `TransactionId` 

That's how I saw it, but maybe we should look into Microsoft's code and take a peek how they do it.
