### ISSUE TITLE
Implement Azure Functions exception handling middleware (`IFunctionsWorkerMiddleware`)

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.webapi#327]
**Is your feature request related to a problem? Please describe.**
Since our Azure Functions project templates will need to run out-of-process to support middleware, we should also adding support for such types of middleware in our Web API library.

**Describe the solution you'd like**
Extract the exception handling functionality in the current Web API `ExceptionHandlingMiddleware` component so that we can re-use it in a new `IFunctionsWorkerMiddleware` component.

**Additional context**
https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#differences-with-net-class-library-functions
https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide

**Comment by fgheysels** [comment]
How do you see this practically ?
Create a separate dll which houses the middleware and package it as yet another nuget package ?
Can we re-use exactly the same classes ?

**Comment by stijnmoreels** [comment]
> How do you see this practically ?
> Create a separate dll which houses the middleware and package it as yet another nuget package ?
> Can we re-use exactly the same classes ?

We already have some Azure Functions-specific packages that takes in additional dependencies that regular Web API projects don't require and should not depend on. There already exists some functionality that is being re-used. The HTTP correlation service, for example, is the exact same functionality behind the scenes and works in both cases. Luckily, we already have a dedicated Azure Functions package which stores extensions on logging, so all these additional Azure Functions middlewares can be located there. They all share the same core library `Arcus.WebApi.Logging.Core` where the shared functionality is stored.

**Comment by stijnmoreels** [comment]
Waiting for [`Microsoft.Azure.Functions.Worker`](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/) to be out of preview.

**Comment by stijnmoreels** [comment]
Waiting for a response on this https://github.com/Azure/azure-functions-dotnet-worker/issues/968 as reliable integration testing without it is hard.
