### ISSUE TITLE
Change target-type of Security related extension methods

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.webapi#329]
We create some extension methods to easily add our custom authentication filters to the ASP.NET pipeline.

These extension methods (for instance `AddSharedAccessKeyAuthenticationOnHeader`) are extension methods on the `FilterCollection` type.  This means we have to call them like this:

```csharp
builder.Services.AddControllers( options => 
    {
        options.Filters.AddSharedAccessKeyAuthenticationOnHeader( ... );
    });
```

Suggestion would be to change these methods so that they extend the `MvcOptions` type.  By doing so, they can be used like this:

```csharp
builder.Services>.AddControllers( options =>
    {
        options.AddSharedAccessKeyAuthenticationOnHeaderFilter( ... );
    });
```

**Comment by stijnmoreels** [comment]
`...OnHeaderFilter` or `...FilterOnHeader` 😅 ?

**Comment by stijnmoreels** [comment]
All changed! 🥳
