### ISSUE TITLE
JSON serialization extensions docs examples on the MVC infrastructure are not using the .NET 6 way of working

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.webapi#331]
**Is your feature request related to a problem? Please describe.**
The feature documentation that describes the JSON serialization extensions on the MVC infrastructure doesn't uses the .NET 6 way of using the `WebApplicationBuilder.AddControllers(...)` but the `IServiceCollections.AddMvc(...)` way of working. 
Related page: https://webapi.arcus-azure.net/features/hosting/formatting

**Describe the solution you'd like**
Use the `WebApplicationBuilder` to describe the code samples for the JSON serialization extensions.
This should be something in the like of:
```csharp
WebApplicationBuilder builder = ...
builder.Services.AddControllers(options =>
{
    options.OnlyAllowJsonFormatting();
    options.ConfigureJsonFormatting(...);
});
```

**Additional context**
Related page: https://webapi.arcus-azure.net/features/hosting/formatting

**Comment by fgheysels** [comment]
IMHO, this has nothing to do with .NET 6, but with ASP.NET.   `AddControllers` has been introduced in ASP.NET Core 3.x if I'm not mistaken.

That aside, we should indeed make sure that our docs are updated and reflect the preferred way of doing things

**Comment by stijnmoreels** [comment]
The `WebApplicationBuilder` instead of using the `IServiceCollection` in the `Startup`, that was this is about. The docs are still using the `Startup.ConfigureServices` and should maybe reflect more the new way of working.
