### ISSUE TITLE
Improve Xml documentation on RequestTrackingAttribute

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.webapi#332]
The current xml documentation on `RequestTrackingAttribute` contains this :

> Represents an endpoint attribute that indicates which endpoints should be withhold from request tracking.

This is not entirely clear imo.  I would just change it to this:

> Specifies that this endpoint must be tracked

It is of course difficult to find a complete covering description, as the attribute can be placed on class and method level.  Next to that, this attribute offers multiple ways to specify which requests should be tracked (specific response-code, only status-codes that fall in a certain range, etc...)

**Comment by stijnmoreels** [comment]
I understand, though the proposed description would lead people to think that the endpoint would only be tracked if that attribute is placed on the endpoint, and that's not the case.
Hmm, maybe something with `...manipulates request tracking...`? As in: `Specifies additional configuration to manipulate the request tracking`?
