### ISSUE TITLE
Open ExceptionHandlingMiddleware for extension

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.webapi#340]
We have our ExceptionHandlingMiddleware component which logs unhandled exceptions to AppInsights and return a http 500 statuscode.

I think it would be good if users can specify what should be logged to application insights, and what should be returned by the middleware to the caller.

An idea to do that, would be to make the `LogException` method `virtual protected` instead of `private`.
We could do something similar for the response that is being returned; move that code to a `virtual protected` method.

Main question would be:  how does this fit in with the helper method which registers the middleware in the pipeline.   I see that a developer might want to inherit from the Arcus ExceptionHandlingMIddleware, but then, he needs to register his custom middleware component that inherits from the Arcus middleware.

Would we be able to do that via 

```csharp
app.UseExceptionHandling<MyExceptionHandlingMiddleware>();
```

That would mean that we need to provide an extension method that takes a type parameter, with the constraint that the type-parameter must inherit from the Arcus ExceptionHandlingMiddleware component.

**Comment by stijnmoreels** [comment]
Yeah, this seems like a good proposal! We already do something similar for the request tracking, so it would be totally in line with that middleware component. I'll summarize:
- [ ] Make `LogException` method `protected virtual` so it can be overriden
- [ ] Add `protected virtual` method to control HTTP response
- [ ] Add `UseExceptionHandling` overload with type constraint
