### ISSUE TITLE
Extra overload for SharedAccessKeyAttribute

### ISSUE THREAD

**Issue by gverstraete** [arcus-azure/arcus.webapi#358]
**Is your feature request related to a problem? Please describe.**
The current code here: https://github.com/arcus-azure/arcus.webapi/blob/master/src/Arcus.WebApi.Security/Authentication/SharedAccessKey/SharedAccessKeyAuthenticationAttribute.cs

supports Azure Keyvault integration which is great! but I'd like an extension to this.

**Describe the solution you'd like**
We are working on a key rotation system, which means that when a new secret version is deployed, the new one & the old one should be still active & be considered as "valid"..

To make it easy, I would make the amount of versions to validate configurable.

Idealy this works together with the Event Grid event when a new version is deployed.

In this way we can have rolling updates on our secrets & api-keys.

Let me know what you think.

**Comment by stijnmoreels** [comment]
Hi Gillian, thx for mentioning.
Have you looked at [this documentation page](https://background-jobs.arcus-azure.net/Features/Security/auto-invalidate-secrets) where we talk about automatic notification of the cache. It also works with the Arcus store, so it can be used for shared access key authentication. The authentication mechanism will call the cached variant from the secret store automatically, and you could notify with Key Vault events when a certain secret should be invalidated by the cache. A background job will then notify the secret store, and eventually, the shared access key authentication will ask for a different secret.

**Comment by gverstraete** [comment]
Hi @stijnmoreels !

Yes, I did look at that documentation :). The main point that I want to make here is that we should be able to have two valid versions of the secret. The last one & the last -1.

Both should be validated with that attribute, and that is something that will need to be added...

It's like in storage accounts, there you have primary & secondary keys. you rotate by updating one of the two, and migrating all your applications to the new one. I want to do something similar here with keyvault secrets.

**Comment by stijnmoreels** [comment]
Aha, ok, hmm. Think this is more something we should add in our Arcus secret store, and not in Web API, as the Azure Key Vault integration here goes via the secret store.

**Comment by gverstraete** [comment]
Yes, but I'd prefer to only have one secret, because secrets have versioning in keyvault.

**Comment by stijnmoreels** [comment]
Done in #380

**Comment by stijnmoreels** [comment]
@gverstraete , we will close this bc it is implemented and provided with a preview version. Feel free to re-open it in case of any problems.
