### ISSUE TITLE
Correlation tracing in application insights

### ISSUE THREAD

**Issue by pim-simons** [arcus-azure/arcus.webapi#369]
**Describe the bug**
My customer is running HTTP Triggered Azure Functions and logging telemetry using Arcus.Observability to Application Insights. 
We are now getting a lot of trace information that we did not get before in Application Insights containing this information:
![image](https://user-images.githubusercontent.com/32359437/182604718-756b3aa1-47e4-412a-9487-a1a5636a3e3c.png)

We don't need/want this information in Application Insights but I cannot find a way to get rid of these traces. 
This seems to have originated when updating to Arcus.WebApi.Logging.AzureFunctions 1.6.0. The code of the application did not change, only the Arcus packages were updated.

Did something change so that these trace warnings are now logged? And is there a way to prevent these trace messages being logged?

**To Reproduce**
Run an HTTP Triggered Azure Function and log information to Application Insights.

**Expected behavior**
These messages are not expected to be logged to Application Insights:
![image](https://user-images.githubusercontent.com/32359437/182605635-586d33af-697a-4cf8-85e0-8b26748d601c.png)

**Comment by stijnmoreels** [comment]
Yeah, this was something that was added since we thought that we would remove the `Operation.IncludeInResponse` property eventually, but we didn't go through with that.
So, after @fgheysels is back, I would want to release v1.6.1 where this is fixed.

For now, you could upgrade to v1.6.1-preview-1 where this won't show up anymore.

**Comment by pim-simons** [comment]
Upgraded to version v1.6.1-preview-1 and did a test, the `Operation correlation ID's cannot be added to response, but the Operation.IncludeInResponse setting was still set` trace messages has indeed disappeared. 

However the `No response header was added given no operation parent ID was found` trace message is still there in the logging. 
Anything that needs to be done to get rid of that message?

**Comment by stijnmoreels** [comment]
> However the No response header was added given no operation parent ID was found trace message is still there in the logging.
Anything that needs to be done to get rid of that message?

No, that one is ok. It means that the incoming request didn't include the operation parent ID header (`Request-Id` as default), and this is a common scenario in the initial request but is probably wrong in a follow-up request/response exchange.

You think we should remove this one? I guess it's logged as warning so people know that there's something missing. (Like not using our cool HTTP client correlation tracking extension 😉 ).

**Comment by pim-simons** [comment]
Could we somehow make it configurable? It is a change since version 1.5.
To me it is not really a warning, more of an informational message. Maybe we could make the level configurable?

**Comment by stijnmoreels** [comment]
> Could we somehow make it configurable? It is a change since version 1.5 that people might not necessarily need or want to see in Application Insights. To me it is not really a warning, more of an informational message. Maybe we could make the level configurable?

Yeah, maybe we can make it a trace as it is indeed not enough 'warning' material and could often by correct. So, yes, we should change it to a lower logging level. Making it configurable is maybe taking things too far as this is very low level stuff, right? Don't think many will interact with it on this low a level, but we could definitely update it to a trace so people know it's just diagnostic (which is what it is, actually). 👍

**Comment by stijnmoreels** [comment]
Let's include this as well in the v1.6.1 fix release 🥳

**Comment by pim-simons** [comment]
> > Could we somehow make it configurable? It is a change since version 1.5 that people might not necessarily need or want to see in Application Insights. To me it is not really a warning, more of an informational message. Maybe we could make the level configurable?
> 
> Yeah, maybe we can make it a trace as it is indeed not enough 'warning' material and could often by correct. So, yes, we should change it to a lower logging level. Making it configurable is maybe taking things too far as this is very low level stuff, right? Don't think many will interact with it on this low a level, but we could definitely update it to a trace so people know it's just diagnostic (which is what it is, actually). 👍

Sounds good to me!

> Let's include this as well in the v1.6.1 fix release 🥳

Awesome! 😄

**Comment by fgheysels** [comment]
I believe the corresponding PR still needs to be modified to make sure that this one message is also considered as a 'trace' and not a 'warning' ?
