### ISSUE TITLE
Add telemetry context option to HTTP client correlation tracking options

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.webapi#370]
**Is your feature request related to a problem? Please describe.**
Currently, when sending a HTTP request with the HTTP client correlation tracking, we aren't able to send any additional telemetry data, while in certain cases this is required (see Azure Functions (in-process)) or very useful for additional information.

**Describe the solution you'd like**
Add an option that let's you a telemetry context to the options. We shouldn't expose directly the `IDictionary<>` as this is a bad practice, we could add a method on the options model to add such a context with a method, like:

```csharp
options.AddTelemetryContext(...);
```

**Additional context**
Discovered by question of @pim-simons

**Comment by pim-simons** [comment]
Sounds like a good solution 👍🏻

**Comment by stijnmoreels** [comment]
Doesn't require much work. Will pick this. 😉
