### ISSUE TITLE
Simplify HttpClient Correlation setup

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.webapi#375]
As I was reviewing [this PR](https://github.com/arcus-azure/arcus/pull/234/files#diff-fc89cef71615c57bdf7c6fffe8ecc1430a8f3e9f130139b384901b57ea464490), I was wondering if we could simplify setting up Http Correlation tracking for HttpClients.

Right now, we need to:

- Register the Http Correlation Service, by calling `AddHttpCorrelation()`
- Make sure that the handler is registered for every HttpClient that we register, by using `WithHttpCorrelationTracking` 
- Make sure that the Http Correlation middleware is used, by calling `UseHttpCorrelation`

Calling `AddHttpCorrelation` and `UseHttpCorrelation` makes sense. However, I was wondering if we could find a way to prevent that users need to call the `WithHttpCorrelationTracking` method on every `HttpClient` that is registered, as I think this is something that might be easily forgotten.

I was thinking if it is possible to register this handler for every registered HttpClient in the `UseHttpCorrelation` method ?

**Comment by stijnmoreels** [comment]
The `UseHttpCorrelation` is the registration of the HTTP correlation middleware component. Any services registered are already build here, so no additional services can be added.

If we would want to limit this, it would have to happen in the `AddHttpCorrelation`, although, it seems that this is very 'magic', no? Hidden behind other stuff.

**Comment by fgheysels** [comment]
It is not possible to just iterate over the registered HttpClients inside the 'UseHttpCorrelation' method, and add those handlers to them ?

**Comment by stijnmoreels** [comment]
> It is not possible to just iterate over the registered HttpClients inside the 'UseHttpCorrelation' method, and add those handlers to them ?

I think not, as they are injected clients, and the container has already been built at that point.
It's different from Azure Functions middleware, where the middleware components are registered during the service registration.

**Comment by stijnmoreels** [comment]
Oh, forgot to mention: people are not obligated to use the `IHttpClientFactory`, they can also directly use their own `HttpClient` with one of our correlation extensions.

**Comment by stijnmoreels** [comment]
This will be simplified with #392 as the `.WithHttpCorrelation()` will no longer be needed.
