### ISSUE TITLE
JwtTokenReader checks on aud instead of sub

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.webapi#399]
**Describe the bug**
We use the `JwtTokenReader` class for backdoor security in our API's.  
The idea of 'backdoor security' is to verify if the incoming request on the API is originating from API Management.   

To achieve this, we add an APIM policy to create a token and send that token to the backend in an additional header.
For instance:
```xml
<authentication-managed-identity resource="target-audience" output-token-variable-name="bearerToken" ignore-error="true" />
        <set-header name="x-managed-identity-token" exists-action="override">
            <value>@((String)context.Variables["bearerToken"])</value>
        </set-header>
```
([More info](https://learn.microsoft.com/en-us/azure/api-management/api-management-authentication-policies#ManagedIdentity))

We pass the resulting token to the backend api and use the `JwtTokenReader` to check if that additional token (x-managed-identity-token) is present and valid.   By valid, we mean:  is the audience correct, as the id that we can pass in in the constructor is supposed to be an audience.

However, I believe that we should not verify the audience.  We should verify the subject of that token to perform backdoor security, as anyone can try to obtain a token for that specific audience and pass in this additional token.   We need to make sure that the token has been requested by API Management instead.

**Comment by fgheysels** [comment]
In hindsight, I think having a constructor which accepts an `applicationId` that represents the audience might be the good choice anyway.  (Although I think we should rename that parameter to `audience`  instead of calling it `applicationId`).

To implement the backdoor - security as described above, we should use the constructor that accepts the 'claimcheck' collection.

**Comment by gverstraete** [comment]
I understand and would agree with this; But I would not break old implementation over this. Let this not be a breaking change!

Related Brain Spin:
But when looking at this today. I'm wondering if we should not create an "in-behalf-token" by API-M in this scenario and let the code validate the only one so we can use this. (https://auth0.com/blog/whats-new-in-dotnet-7-for-authentication-and-authorization/)...

Thinking while writing, but at the moment that behavior is not supported by Azure API-M, So we'll need to stick to this 2 token behavior.

**Comment by fgheysels** [comment]
> I understand and would agree with this; But I would not break old implementation over this. Let this not be a breaking change!
> 
> Related Brain Spin: But when looking at this today. I'm wondering if we should not create an "in-behalf-token" by API-M in this scenario and let the code validate the only one so we can use this. (https://auth0.com/blog/whats-new-in-dotnet-7-for-authentication-and-authorization/)...
> 
> Thinking while writing, but at the moment that behavior is not supported by Azure API-M, So we'll need to stick to this 2 token behavior.



> I understand and would agree with this; But I would not break old implementation over this. Let this not be a breaking change!

Indeed.  That is also what I'm saying in the 2nd post here.  We should keep it as is, except we should consider renaming the parameter.  

> Related Brain Spin: But when looking at this today. I'm wondering if we should not create an "in-behalf-token" by API-M in this scenario and let the code validate the only one so we can use this. (https://auth0.com/blog/whats-new-in-dotnet-7-for-authentication-and-authorization/)...
> 
> Thinking while writing, but at the moment that behavior is not supported by Azure API-M, So we'll need to stick to this 2 token behavior.
You also do not want to loose the token of the original caller, as there might be access roles etc in there.
If APIM would support an on-behalf of token flow, we could indeed consider it, as I understood that this flow sort of 'merges' the existing token into a new token.

**Comment by gverstraete** [comment]
Renaming the parameter, but don't handle it as breaking change please :).

**Comment by stijnmoreels** [comment]
@fgheysels , I think we choose to use `applicationId` bc that is the name that is used in APIM (instead of `clientId`).

**Comment by fgheysels** [comment]
> @fgheysels , I think we choose to use `applicationId` bc that is the name that is used in APIM (instead of `clientId`) when connecting to Azure AD.

Possibly.  However, when you use this code and you see that this method accepts a parameter`applicationId` it doesn't really reaveal to the user what you should pass in.  When it is called 'audience', you know that you need to pass in the audience string on which we will validate.
The fact that you should pass in the applicationId of APIM is something that can be mentioned in the documentation.
On the other hand, passing in the APIM applicationId to check on 'audience' doesn't really make sense imo. (Especially not if you want to implement backdoor security)

**Comment by gverstraete** [comment]
if it would be only audience I would agree, but you also validate on the open-id configuration right?. In the end we need to change, just make it so it's clear for everyone how to upgrade!

**Comment by fgheysels** [comment]
I think it is a good idea to start with renaming that parameter.

**Comment by fgheysels** [comment]
Should we bump the major version on the release that contains this change ?

**Comment by stijnmoreels** [comment]
> Should we bump the major version on the release that contains this change ?

We could include all these TODO breaking changes with it: https://github.com/arcus-azure/arcus.webapi/issues?q=is%3Aissue+is%3Aopen+label%3Abreaking-change

**Comment by fgheysels** [comment]
Sounds good to me.  Just wonder if the replacements for those breaking changes are 'old enough' ?

**Comment by stijnmoreels** [comment]
> Sounds good to me. Just wonder if the replacements for those breaking changes are 'old enough' ?

Yeah, that's a good question. Not sure. Was thinking: maybe we can maybe create factory methods with a more descriptive name instead of trying to rename constructor parameters? That way, we won't have any breaking changes.

**Comment by gverstraete** [comment]
> > Sounds good to me. Just wonder if the replacements for those breaking changes are 'old enough' ?
> 
> Yeah, that's a good question. Not sure. Was thinking: maybe we can maybe create factory methods with a more descriptive name instead of trying to rename constructor parameters? That way, we won't have any breaking changes.

If I remember correctly, this is used as annotation. So then a factory might not be so ideal :) Maybe just mark it as a bugfix! :)
