### ISSUE TITLE
System.TypeLoadException : Could not load type 'Microsoft.Extensions.DependencyInjection.IServiceCollectionExtensions' from assembly 'Arcus.WebApi.Logging.Core, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by wimvangoethem** [arcus-azure/arcus.webapi#419]
After updating from 1.6.1 to 1.7.0 Arcus.WebApi.Logging our tests which use our Startup classes from our Api's started throwing this error when running ConfigureServices. We already temporarily solved the issue with the switch to W3C by explicitly choosing Hierarchical. A ticket will be made on our side to switch to w3c. It just seems weird that the default mode triggers this type of error. 

We're using IServiceCollection AddHttpCorrelation(this IServiceCollection services, Action<HttpCorrelationInfoOptions> configureOptions) 
from the package.

**Comment by fgheysels** [comment]
The `AddHttpCorrelation` extension method has been moved to the Arcus.Observability.Correlation package, so normally this should be covered.

If I understand correctly, you're not running into that error when using Hierarchical correlation instead of W3C correlation ?  

Could it be that you are still referring / using the `AddHttpCorrelation` method that has been marked as obsolete in previous versions of Arcus ?  Since that extension method is no longer available in the current version of Arcus.

**Comment by fgheysels** [comment]
I think it is weird that this is solved by reverting back to Hierarchical correlation but still using Arcus.WebApi 1.7.0, as this error is actually an error that indicates that a specific extension method cannot be found.
The `AddHttpCorrelation` extension method is no longer present in `Arcus.WebApi.Logging.Core` but exists now in `Arcus.WebApi.Logging`.

Can you remove the reference to the `Arcus.WebApi.Logging.Core` package and replace it with a reference to `Arcus.WebApi.Logging` instead ?

**Comment by wimvangoethem** [comment]
As far As I can see it's not a depricated method that we are using. We are indeed using a direct depency Logging.Core, but it wouldn't matter since WebApi.Logging seems to have a subdependency on it anyway

**Comment by wimvangoethem** [comment]
We removed the direct reference and now it does indeed use the extensions from Logging directly

**Comment by fgheysels** [comment]
You fixed it by using the 'Hierarchical' correlation option, but to be honest, that is not a long-term solution as the 'Hierarchical' correlation strategy is deprecated.
https://learn.microsoft.com/en-us/azure/azure-monitor/app/correlation#correlation-headers-using-w3c-tracecontext

**Comment by wimvangoethem** [comment]
Indeed, a ticket to switch over our code has been made, but it's going to be a big adjustment, so in the meantime a temporary fix to resolve our update issues.

**Comment by stijnmoreels** [comment]
@wimvangoethem , we'll close this one, but feel free to re-open it or create a new issue if this or another problem occurs. 👍 
Thx for using Arcus! 🎉
