### ISSUE TITLE
Unable to resolve service for type 'Arcus.WebApi.Logging.Correlation.HttpCorrelation'

### ISSUE THREAD

**Issue by pim-simons** [arcus-azure/arcus.webapi#422]
**Describe the bug**
I updated the following packages:
![image](https://user-images.githubusercontent.com/32359437/210086159-11121583-3248-4218-845d-14445a695af1.png)

Did not do any other changes and an HTTP Triggered Azure Function that was working correctly is now failing with this error: `Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type 'Arcus.WebApi.Logging.Correlation.HttpCorrelation' while attempting to activate 'somefunction'`

I don't see any breaking changes listed [here](https://github.com/arcus-azure/arcus.webapi/releases/tag/v1.7.0), so I would expect my code would keep working.

**To Reproduce**
Update from an existing Azure Function from version 1.6.1 to 1.7.0.

**Expected behavior**
No error and a working Azure Function.

**Comment by stijnmoreels** [comment]
Yes, there are no breaking changes, but you have to use `AzureFunctionsInProcessHttpCorrelation` instead of `HttpCorrelation` in W3C HTTP correlation (which is set default). This is described in the docs as well: https://webapi.arcus-azure.net/Features/correlation-azure-functions

**Comment by pim-simons** [comment]
My case is that for now I want to stay on the `HttpCorrelation` but update to the latest version of the packages. I will update later on to W3C. 
I added `options.Format = HttpCorrelationFormat.Hierarchical;` in the startup file, but still the same error. Anything else I should be changing?

**Comment by stijnmoreels** [comment]
Ah, maybe call the extension on the `IServiceCollection` itself. That way you will get the original stuff like before:

```csharp
builder.Services.AddHttpCorrelation(options => options.Format = HttpCorrelationFormat.Hierarchical);
```

**Comment by stijnmoreels** [comment]
Working on it. Was indeed something missing here.
For now, you can maybe install the `Arcus.WebApi.Logging` additional to it, and use the extension normally used for Web API. That will get you the `HttpCorrelation` instance registered.

**Comment by pim-simons** [comment]
> Working on it. Was indeed something missing here. For now, you can maybe install the `Arcus.WebApi.Logging` additional to it, and use the extension normally used for Web API. That will get you the `HttpCorrelation` instance registered.

No worries, will revert back to the old packages for now and wait for the fix. 
Thanks for the quick action!

**Comment by pim-simons** [comment]
Tested with version 1.7.1 and added `options.Format = HttpCorrelationFormat.Hierarchical;` in the Startup this now works correctly 👍🏻 Closing the issue.

**Comment by stijnmoreels** [comment]
> Tested with version 1.7.1 and added `options.Format = HttpCorrelationFormat.Hierarchical;` in the Startup, this now works correctly 👍🏻 Closing the issue.

Oh, that's great. Super! 👍
