### ISSUE TITLE
OAuth authorization integration when using SwaggerUI in an API

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.webapi#45]
It's always a hassle when you want to test/execute an API operation using SwaggerUI when the API operation requires a Jwt bearer token.
It would be helpfull if there is an ability that allows you to call the authority server that issues a token from Swagger UI and use that token to invoke the API operations from within SwaggerUI.

**Describe the solution you'd like**
This can be implemented by creating a custom `Swashbuckle.IOperationFilter`.

**Comment by fgheysels** [comment]
As I see it, this feature does not belong in any of the existing packages in arcus.webapi, so I assume we'll need to create a new one.
Any suggestions on the name ?  arcus.webapi.swagger ? arcus.webapi.swaggerextensions ? arcus.webapi.swagger.extensions ? ... ?

**Comment by tomkerkhove** [comment]
This certainly sounds like an interesting one, thanks for the suggestion!

Given OpenAPI is around and this is mainly just for Swashbuckle I'm considering `arcus.webapi.openapi.extensions.swashbuckle` or `arcus.webapi.openapi.extensions`. Thoughts?

**Comment by fgheysels** [comment]
> Given OpenAPI is around and this is mainly just for Swashbuckle I'm considering `arcus.webapi.openapi.extensions.swashbuckle` or `arcus.webapi.openapi.extensions`. Thoughts?

I'd prefer the shortest one (`arcus.webapi.openapi.extensions`).
 
> Do you by any chance have a snippet that elaborates on how it works?

It would come down to, instead of having a line like this in your ConfigureServices method to enable Swagger for your API:
```csharp
services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "My Api", Version = "v1" });
            });
```
You'd introduce it like this:
```csharp
services.AddSwaggerGenWithOAuthEnabledClient(
                swaggerDocName: "v1",
                apiMetaData: new Info { Title = "My Api", Version = "v1" },
                authorityUrl: "http://myTokenProvider",
                scopes: new Dictionary<string, string>
                        {
                            { "scope1", "Scope description" }
                        });
```
(I'd like to find a better name for the `AddSwaggerGenWithOAuthEnabledClient` method however :) ).

This would make sure that the Swagger UI page has an Authorize button and when clicking upon that button, an access token is requested from the authority (token issuer) for the selected scopes.

**Comment by tomkerkhove** [comment]
@fgheysels 	I think we're good to go with this one, correct?

**Comment by tomkerkhove** [comment]
Closing for now, feel free to re-open if required
