### ISSUE TITLE
Provide easy way to report health check information

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#50]
Provide an easy way to report health check information that is capable of being documented as well.

### Package
Would suggest introducing something along the lines of `Arcus.WebApi.Operations.Health`.

### Implementation
Would be good to refactor this further into something like the following:
```csharp
[Route("api/v1/health")]
public class HealthController : OperationsControllers
{
    public HealthController(HealthCheckService healthCheckService)
        : base(healthCheckService)
    {
    }

    /// <summary>
    ///     Get Health
    /// </summary>
    /// <remarks>Provides an indication about the health of the API</remarks>
    /// <response code="200">API is healthy</response>
    /// <response code="503">API is unhealthy or in degraded state</response>
    [HttpGet]
    [ProducesResponseType(typeof(HealthReport), (int)HttpStatusCode.OK)]
    [SwaggerOperation(OperationId = "Health_Get")]
    public async Task<IActionResult> Get()
    {
            return await CreateHealthReport();
    }
}
```

Initial idea: https://blog.tomkerkhove.be/2019/07/04/health-checks-with-openapi-specifications/

**Comment by tomkerkhove** [comment]
Do you like my suggestion @stijnmoreels 	?

**Comment by stijnmoreels** [comment]
> Do you like my suggestion @stijnmoreels ?

Not sure, the `OperationsControllers` should inherit from `ControllerBase` I guess?
I see your point in having a place to add functionality related to health...

Could we make our own health service that should get registered and that can be pulled via dependency? That way the user is free to inherit from any parent he/she/X wants?

**Comment by tomkerkhove** [comment]
ASP.NET Core already leverages that, but they do not decorate the endpoints they expose with OpenAPI.

This would simplify this, but you can read more about it in this [blog post](https://www.codit.eu/blog/documenting-asp-net-core-health-checks-with-openapi/).

Inheriting might not be ideal indeed but it's a means to avoid always doing the same if based on health report:
```csharp
public async Task<IActionResult> Get()
{
    var report = await _healthCheckService.CheckHealthAsync();

    return report.Status == HealthStatus.Healthy ? Ok(report) : StatusCode((int)HttpStatusCode.ServiceUnavailable, report);
}
```

**Comment by stijnmoreels** [comment]
Extension method on the existing ASP.NET Core service for now?

**Comment by tomkerkhove** [comment]
Then you have to know you need that class, interesting. We could do both.

Tom Kerkhove
Azure Architect at Codit, Microsoft Azure MVP

________________________________

**Comment by fgheysels** [comment]
I like the approach of the `HealthController`, but I wonder if this is something that should be in Arcus.  It's a very simple class with a just one method (which is also quite simple).  
I think it would be more usefull if we could create some additional `IHealthCheck` implementations that are customizeable and reuseable.  ( Db healthcheck (if it doesn't exist already), ... )

**Comment by tomkerkhove** [comment]
DB health check are already supported - https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2#database-probe

Ok then we'll leave it out-of-scope
