### ISSUE TITLE
Provide support for out-of-the-box correlation

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#67]
**Is your feature request related to a problem? Please describe.**
Provide support for out-of-the-box correlation on both the operation & transaction level.

Every request should allow consumers to specify a transaction id by passing the `X-Transaction-Id` header. If this is not specified, one will be generated.

Internally this transaction id and operation id can be used internally for correlating telemetry.

Every response should return the used correlation information via the following headers:
- `X-Transaction-Id` - The generated or specified transaction id
- `RequestId` - The unique id that identifies this operation.

This information should also be able to be retrieved further down the application if they wish to use it.

**Describe the solution you'd like**
Middleware should be provided that handles this for every call, and registers the information for others to use.

[Request Features](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/request-features?view=aspnetcore-2.2) are a great approach to achieve this.

The headers mentioned above should just be default headers that can be configured to use different ones if the consumers wish to do so.

**Additional context**
By registering this for other components to use it, we can use it for things like telemetry enrichments.

This should be provided via a new package, my proposal would be `Arcus.WebApi.Telemetry.Correlation`.

**Comment by tomkerkhove** [comment]
I've done this before and will pick this up

**Comment by tomkerkhove** [comment]
While it doesn't fully overloap with it, we should check if we should use [CorrelationId📦](https://github.com/stevejgordon/CorrelationId).

**Comment by tomkerkhove** [comment]
# Design Proposal
## Configuring correlation
Registration should be very simple:
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseCorrelationId();

    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }

    app.UseMvc();
}
```

If they want to have more control, they can use an overload to configure the behavior:
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseCorrelationId(correlationOptions => {
        // Configure correlation
    });

    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }

    app.UseMvc();
}
```

### Configuration Options
It allows users to configure the following configuration options:
- `Transaction.HeaderName` (default: `X-Transaction-Id`)
- `Transaction.AllowInRequest` (default: `true`)
- `Transaction.IncludeInResponse` (default: `true`)
- `Transaction.Enabled` (default: `true`)
- `Transaction.GenerateWhenNotSpecified` (default: `true`)
- `Operation.HeaderName` (default: `RequestId`)
- `Operation.IncludeInResponse` (default: `true`)
- `Operation.Enabled` (default: `true`)

## Interacting with correlation information

Correlation information is only powerful if you can get access to it.

My suggestion would be to :
- Provide a `ICorrelationInfo` that gives you a `OperationId` (or `RequestId`?) & `TransactionId`
- Register correlation as [a feature on the request](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/request-features?view=aspnetcore-2.2)

If you agree, I can pick this up or provide a sample if it would help.

**Comment by stijnmoreels** [comment]
Yeah, I think that's a good approach. Not sure if I understand every configuration option, but that's OK I guess for now. We'll see in the PR's and tests how it can be used I guess.

**Comment by tomkerkhove** [comment]
What do you think @fgheysels ?

**Comment by fgheysels** [comment]
I agree with the configuration part.  I just don't immediately see how the interaction part is going to be done.

**Comment by stijnmoreels** [comment]
> I agree with the configuration part. I just don't immediately see how the interaction part is going to be done.

When given a `HttpContext.RequestServices`, you can retrieve a previously registered service. Which could be in this case our correlation.

**Comment by tomkerkhove** [comment]
It is not really how it will be but let me work on a proposal PR that would indicate the idea if you agree on the approach?

**Comment by scleynen** [comment]
Have you checked this one? Isn't it doing something similar? https://github.com/skwasjer/Correlate

**Comment by stijnmoreels** [comment]
The correlation we want to add to the Arcus.WebApi repo should be able to:
1. Add uniquely generate **operation ID** to the incoming request (not overwritable by request)
2. Add uniquely **transaction ID** either by (1)  us, will be generated, or (2) specified in request
3. Access to both ID's anywhere in the application
4. (Optional) we want to use the correlation in a non-ASP.NET context, so we can use it in the Arcus.Messaging repo

**Comment by stijnmoreels** [comment]
### [Correlate](https://github.com/skwasjer/Correlate)
✔️ An overwritable **operation ID** can be given to the request, which gets generated if not present with
```csharp
services.AddCorrelate(options => options.RequestHeaders = new[] { "x-Correlation-ID"  });
````

**Comment by stijnmoreels** [comment]
### [CorrelationId](https://github.com/stevejgordon/CorrelationId)

✔️ When no correlation ID can be retrieved from the request header, the ID can be generated:
```csharp
app.UseCorrelationId(new CorrelationOptions
{
    UseGuidForCorrelationId = true // (default: false)
```
When the `UseGuidForCorrelationId ` is `false`, then the ID gets retrieved from the `TraceIdentifier` of the request.

✔️ The correlation can be included in the response, when using:
```csharp
app.UseCorrelationId(new CorrelationOptions 
{
    IncludeInResponse = true // (default: true)
});
```

**Comment by tomkerkhove** [comment]
Thanks for the good overview @stijnmoreels - Is it safe to say that [Correlate](https://github.com/skwasjer/Correlate) doesn't depend on ASP.NET Core or not?

If so, can we build on top of that?

**Comment by stijnmoreels** [comment]
> Thanks for the good overview @stijnmoreels - Is it safe to say that [Correlate](https://github.com/skwasjer/Correlate) doesn't depend on ASP.NET Core or not?

Yep, indeed; has a core package with the abstractions and main functionality.
 
> If so, can we build on top of that?

That may be possible yes; maybe some types could be missleading, but I think it can be done.

**Comment by tomkerkhove** [comment]
Let's create a prototype based on that approach then, ok for you?

**Comment by tomkerkhove** [comment]
Thanks for the tip @scleynen!

**Comment by stijnmoreels** [comment]
> Let's create a prototype based on that approach then, ok for you?

Seems like if I want to create atop of that; I'll have to create a lot of duplicate classes because the library uses a fixed data class with a single ID and we need two. This data class is rooted directly in the abstractions.

**Comment by stijnmoreels** [comment]
Seems like we may have to reconsider this when using .NET Core 3.0
https://devblogs.microsoft.com/aspnet/improvements-in-net-core-3-0-for-troubleshooting-and-monitoring-distributed-apps/

**Comment by tomkerkhove** [comment]
And why is that? Because of the header names or? Don't really see major issues and names are easily changed.

**Comment by stijnmoreels** [comment]
> And why is that? Because of the header names or? Don't really see major issues and names are easily changed.

I think with .NET Core 3.0, there already exists a built-in correlation approach for apps; we may want to use that?

**Comment by tomkerkhove** [comment]
I would have to read the whole post but they are only talking about correlation in the concept of logs, not that they propagate it back to the user or did I miss that part?

Needless to say that we should aim to build on top of it instead of competing with it, but we have to keep in mind that we're also working with .NET Core 2.X

**Comment by stijnmoreels** [comment]
I think we can close this?

**Comment by tomkerkhove** [comment]
Yes
