### ISSUE TITLE
Improve documentation on Shared Access Key Filter

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.webapi#73]
**Describe the bug**
The documentation section on implementing the shared access key authentication filter shows that the `ICachedSecretProvider` is a scoped service.
IMHO, it does not really make sense to have this provider as a scoped service, since this would mean that a new `ICachedSecretProvider` is instantiated per request.
I think it makes more sense to have the `ICachedSecretProvider` configured as a singleton, since that would imply a more 'effective' cache.

**Comment by tomkerkhove** [comment]
Agreed, thanks for the PR!
