### ISSUE TITLE
Should the SharedAccessKeyAuthentication filter retry when the key doesn't match?

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.webapi#76]
The `SharedAccessKeyAuthenticationFilter `verifies if the access-key in the header matches with the secrete that is retrieved by the `ICachedSecretProvider` (or `ISecretProvider`).
If the keys do not match, we're given a 401 response.

I'm wondering if the `SharedAccessKeyAuthenticationFilter ` should retry (only once) if the keys do not match ? 
Suppose an incoming request uses the latest api key, but the cache that is used by the filter is still using the old version, a 401 will be returned.   
Should we in this case perform another request to the secret-provider (if using `ICachedSecretProvider` and bypass the cache, or is this too far-fetched ?

**Comment by tomkerkhove** [comment]
Hm interesting case - Is it because the header is not correct or is it because of stale data? How do we identify that?

If we skip the cache to get the latest, then we should somehow timestamp that to avoid hitting the backing provider all the time.

**Comment by fgheysels** [comment]
I've an idea for this, so I'll come up with a PR soon.  Maybe we can discuss it further once the PR is there.

**Comment by tomkerkhove** [comment]
Sounds good to me, thanks!

Tom Kerkhove
Architect - Microsoft Azure Advisor & MVP
m: +32 473 70 10 74
tom.kerkhove@codit.eu | www.codit.eu

**Comment by tomkerkhove** [comment]
Any update on this @fgheysels or shall we park it for now?

**Comment by fgheysels** [comment]
I remember that I was working on a small implementation of the idea I had, but it didn't work out.  Think we can park it.

**Comment by fgheysels** [comment]
> I remember that I was working on a small implementation of the idea I had, but it didn't work out. Think we can park it.

Should I close this issue ?

**Comment by tomkerkhove** [comment]
Makes sense!
