### ISSUE TITLE
Provide support for querystring value in SharedAccessKeyAuthenticationFilter

### ISSUE THREAD

**Issue by SamVanhoutte** [arcus-azure/arcus.webapi#82]
__Problem description:__
Two scenarios:
1. __oAuth__: When implementing a custom API that handles the Authorization call back in an oAuth2 redirect, there is a state query string parameter being sent.  In order to validate the incoming request being authentic, it would be great if the operation to handle that Authorization callback could be tagged not just with the Header validation, but also with the QueryString validation.
1. __Event Grid web hooks__: At this moment, Event Grid can't still add headers for security when configuring a web hook as event handler.

__Proposed Solution__:
- Update the [SharedAccessKeyAuthenticationFilter](https://github.com/arcus-azure/arcus.webapi/blob/master/src/Arcus.WebApi.Security.Authentication/SharedAccessKey/SharedAccessKeyAuthenticationFilter.cs) class to allow configuration for QueryString instead of Header validation as well. 
- Allow the configuration by adding a constructor overload in the [SharedAccessKeyAuthenticationAttribute](https://github.com/arcus-azure/arcus.webapi/blob/master/src/Arcus.WebApi.Security.Authentication/SharedAccessKey/SharedAccessKeyAuthenticationAttribute.cs) class, to indicate where to look for the secret.  (keeping the default to the header obviously)

**Comment by tomkerkhove** [comment]
Is this something you'd like to pick up @stijnmoreels or want me to work on it?

@SamVanhoutte just to be clear - It's going to be one or the other or want to check both? If both, what if they are both defined?

**Comment by stijnmoreels** [comment]
Yes, no problem, I can work on that.
Authorization info in the URL doesn't seem quite security recommended though.

**Comment by SamVanhoutte** [comment]
@tomkerkhove - there's no hurry in this.  could be an easy thing for someone "new" to the project as well.
@tomkerkhove - I don't see scenarios where **both** header+querystring would be needed.
@stijnmoreels - agree I'd always prefer passing the information in the header, but sometimes the consuming app (like in my two scenarios mentioned initially) don't have or give this option.

**Comment by tomkerkhove** [comment]
Good point @SamVanhoutte.

Let's give this a few weeks @stijnmoreels and if nobody picked it up, we can do it.

**Comment by tomkerkhove** [comment]
René Bik will pick this up
