### ISSUE TITLE
GitHub release task can't get initial commit

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.webapi#88]
**Describe the bug**
No correct release can be made for the Arcus webapi repo because the GitHub release task fails with an `can't find initial release` error.
All the required parameters are correctly filled out (repo name and release notes).

Example: https://dev.azure.com/codit/Arcus/_build/results?buildId=39510&view=results

**To Reproduce**
Run release of Arcus web app.

**Expected behavior**
A new GitHub release is created.

**Comment by tomkerkhove** [comment]
Transfering to Arcus Web API as the issue lies here.

**Comment by tomkerkhove** [comment]
This worked before so should be ok, but verified and still has admin priviledges.
