### ISSUE TITLE
Provide support for .NET Core 2.2 & 3.0

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#91]
We need to verify if we have decent support for .NET Core 3.0 and what is blocking us.

In order to achieve that, we should run our whole CI pipelines against both .NET Core 2.2 & .NET Core 3.0.

**Comment by stijnmoreels** [comment]
So job templates with parameter on dotnet version, running on a dotnet core 2 version source code to support both?

**Comment by tomkerkhove** [comment]
Yes, I think that would be the best approach but run it on our .NET Standard 2.0 codebase.

If we are not using .NET STandard yet, we'll have to change that.

**Comment by stijnmoreels** [comment]
> If we are not using .NET STandard yet, we'll have to change that.

Just checked, all projects are on netstandard2.0, but the unit tests for running the test API. That one is on netcoreapp2.0. But shouldn't be a problem I think?

**Comment by tomkerkhove** [comment]
Ideally we run the tests against both versions, if it's not too much of a hassle

**Comment by stijnmoreels** [comment]
Hmm, maybe we could for the build template just run it twice, one for each version?
No need for a job template then.

**Comment by tomkerkhove** [comment]
I think it's best to just run the whole pipeline for every framework, otherwise there will be too much duplication

**Comment by stijnmoreels** [comment]
Ah maybe we can just trigger the build twice with another variable every time.

**Comment by tomkerkhove** [comment]
Define trigger twice - The build should manage everything for us.

Good example is https://dev.azure.com/dnceng/public/_build/results?buildId=395518 which is based on https://github.com/aspnet/Extensions/blob/master/azure-pipelines.yml imo.

Same process, different targets.

**Comment by stijnmoreels** [comment]
> Define trigger twice - The build should manage everything for us.
> 
> Good example is https://dev.azure.com/dnceng/public/_build/results?buildId=395518 which is based on https://github.com/aspnet/Extensions/blob/master/azure-pipelines.yml imo.
> 
> Same process, different targets.

As far as I can understand, the example you'v shown is about a job template where you run through a list of jobs. It's something we also can do; but I can't find your reference to "Define trigger twice"?

**Comment by tomkerkhove** [comment]
> Ah maybe we can just trigger the build twice with another variable every time.

It was based on your remark here where it's not clear what you mean with "trigger the build twice".

Personally I think job templates will be the best approach as we want to run the same job against different frameworks and it's supported out-of-the-box
